name: Test
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest and airflow
      run: |
        pytest
        airflow tasks test hse_cases extract 2021-04-07
        airflow tasks test hse_cases transform 2021-04-07
        airflow tasks test hse_cases load 2021-04-07
        airflow tasks test hse_counties extract 2021-04-07
        airflow tasks test hse_counties transform 2021-04-07
        airflow tasks test hse_counties load 2021-04-07
        airflow tasks test hse_swabs extract 2021-04-07
        airflow tasks test hse_swabs transform 2021-04-07
        airflow tasks test hse_swabs counties 2021-04-07
